name: Version Bump

on:
  push:
    branches:
      - develop

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Latest Commit
#       uses: actions/checkout@v2

#     - name: Bump Version
#       id: bump
#       uses: nnichols/maven-version-bump-action@v3
#       with:
#         github-token: ${{ secrets.github_token }}

#     - name: Print Version
#       run: "echo 'New Version: ${{steps.bump.outputs.version}}'"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures that the action runs over multiple commits

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package

      - name: Increment version
        id: increment-version
        uses: RichardInnocent/semantic-versioning-maven@v0.0.34
        with:
          access-token: ${{ secrets.github_token }}

      # Everything below here shows how you might use the results of the action...

      - name: Print if version changed
        if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
        run: echo "The new version is now $new_version"
        env:
          new_version: ${{ steps.increment-version.outputs.new-version }}